//Данные
let galleryDate = [
  {
    id: randomId(),
    imgUrl: './images/1.jpg',
    imgMinUrl: './images/min/1.jpg',
    class: 'reports',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/2.jpg',
    imgMinUrl: './images/min/2.jpg',
    class: 'portraits',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/3.jpg',
    imgMinUrl: './images/min/3.jpg',
    class: 'reports',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/4.jpg',
    imgMinUrl: './images/min/4.jpg',
    class: 'portraits',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/5.jpg',
    imgMinUrl: './images/min/5.jpg',
    class: 'portraits',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/videos/1.mp4',
    imgMinUrl: './images/min/3.jpg',
    desc: 'реклама моршинской',
    class: 'реклама',
    type: 'video',
    viewing: 'video',
  },
  {
    id: randomId(),
    imgUrl: './images/6.jpg',
    imgMinUrl: './images/min/6.jpg',
    class: 'reports',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/7.jpg',
    imgMinUrl: './images/min/7.jpg',
    class: 'weddings',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/8.jpg',
    imgMinUrl: './images/min/8.jpg',
    class: 'weddings',
    type: 'photo',
  },
  {
    id: randomId(),
    imgUrl: './images/videos/1.mp4',
    imgMinUrl: './images/min/1.jpg',
    desc: 'реклама нижнего белья',
    class: 'reports',
    type: 'video',
    viewing: 'video',
  },
];
