//Данные
let galleryDate = [
  //Портреты
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-1.jpg',
    imgMinUrl: './images/portraits-1-min.jpg',
    ru: { class: 'Портреты', type: 'Фото', desc: 'Портрет мужчины' },
    uk: { class: 'Портрети', type: 'Фото', desc: 'Портрет чоловіка' },
    en: { class: 'Portraits', type: 'Photo', desc: 'Portrait of a man' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-2.jpg',
    imgMinUrl: './images/portraits-2-min.jpg',
    ru: { class: 'Портреты', type: 'Фото', desc: 'Девушка в поле' },
    uk: { class: 'Портрети', type: 'Фото', desc: 'Дівчина в полі' },
    en: { class: 'Portraits', type: 'Photo', desc: 'Girl in the field' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-3.jpg',
    imgMinUrl: './images/portraits-3-min.jpg',
    ru: { class: 'Портреты', type: 'Фото', desc: 'Портрет военного' },
    uk: { class: 'Портрети', type: 'Фото', desc: 'Портрет військового' },
    en: {
      class: 'Portraits',
      type: 'Photo',
      desc: 'Portrait of a military man',
    },
  },

  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-4.jpg',
    imgMinUrl: './images/portraits-4-min.jpg',
    ru: { class: 'Портреты', type: 'Фото', desc: 'Девушка в платке' },
    uk: { class: 'Портрети', type: 'Фото', desc: 'Дівчина в хустці' },
    en: { class: 'Portraits', type: 'Photo', desc: 'Girl in a headscarf' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-5.jpg',
    imgMinUrl: './images/portraits-5-min.jpg',
    ru: { class: 'Портреты', type: 'Фото', desc: 'Девушка с букетом' },
    uk: { class: 'Портрети', type: 'Фото', desc: 'Дівчина з букетом' },
    en: { class: 'Portraits', type: 'Photo', desc: 'Girl with a bouquet' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-6.jpg',
    imgMinUrl: './images/portraits-6-min.jpg',
    ru: {
      class: 'Портреты',
      type: 'Фото',
      desc: 'Урбанистический портрет мужчины',
    },
    uk: {
      class: 'Портрети',
      type: 'Фото',
      desc: 'Урбаністичний портрет чоловіка',
    },
    en: { class: 'Portraits', type: 'Photo', desc: 'Urban portrait of a man' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/portraits-7.jpg',
    imgMinUrl: './images/portraits-7-min.jpg',
    ru: {
      class: 'Портреты',
      type: 'Фото',
      desc: 'Девушка с мыльными пузырями',
    },
    uk: {
      class: 'Портрети',
      type: 'Фото',
      desc: 'Дівчина з мильними бульбашками',
    },
    en: { class: 'Portraits', type: 'Photo', desc: 'Girl with soap bubbles' },
  },
  //Репортаж
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-1.jpg',
    imgMinUrl: './images/reportage-1-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-2.jpg',
    imgMinUrl: './images/reportage-2-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-3.jpg',
    imgMinUrl: './images/reportage-3-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-4.jpg',
    imgMinUrl: './images/reportage-4-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-7.jpg',
    imgMinUrl: './images/reportage-7-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-8.jpg',
    imgMinUrl: './images/reportage-8-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-9.jpg',
    imgMinUrl: './images/reportage-9-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/reportage-10.jpg',
    imgMinUrl: './images/reportage-10-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Фото',
      desc: 'Репортаж',
    },
    uk: {
      class: 'Репортаж',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Reportage', type: 'Photo', desc: '' },
  },

  //свадьба

  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-1.jpg',
    imgMinUrl: './images/wedding-1-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-2.jpg',
    imgMinUrl: './images/wedding-2-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-3.jpg',
    imgMinUrl: './images/wedding-3-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-4.jpg',
    imgMinUrl: './images/wedding-4-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-5.jpg',
    imgMinUrl: './images/wedding-5-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-6.jpg',
    imgMinUrl: './images/wedding-6-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  {
    id: randomId(),
    viewing: 'photo',
    imgUrl: './images/wedding-7.jpg',
    imgMinUrl: './images/wedding-7-min.jpg',
    ru: {
      class: 'Свадьба',
      type: 'Фото',
      desc: 'Свадьба',
    },
    uk: {
      class: 'Весілля',
      type: 'Фото',
      desc: '',
    },
    en: { class: 'Wedding', type: 'Photo', desc: '' },
  },
  //Video
  {
    id: randomId(),
    viewing: 'video',
    videoType: 'video/mp4',
    imgUrl: './images/videos/1.mp4',
    imgMinUrl: './images/portraits-7-min.jpg',
    ru: {
      class: 'Репортаж',
      type: 'Видео',
      desc: 'реклама нижнего белья и что то еще, веники',
    },
    uk: { class: 'Портрети', type: 'Відео', desc: 'Портрет мужчины' },
    en: { class: 'Portriect', type: 'Video', desc: 'Портрет мужчины' },
  },
  {
    id: randomId(),
    viewing: 'video',
    videoType: 'video/mp4',
    imgUrl: './images/videos/2.mp4',
    imgMinUrl: './images/portraits-6-min.jpg',
    ru: {
      class: 'Что то еще',
      type: 'Видео',
      desc: 'Что то еще',
    },
    uk: { class: 'Что то еще', type: 'Відео', desc: 'Что то еще' },
    en: { class: 'Something else', type: 'Video', desc: 'Something else' },
  },
];
